version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: syncstock_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: syncstock_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
