# Generated by Django 5.0.7 on 2024-08-18 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.category'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.location'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.location'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalcurrentinventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.category'),
        ),
        migrations.AlterField(
            model_name='totalcurrentinventory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='syncstock.company'),
        ),
    ]
