# Generated by Django 5.0.7 on 2024-08-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncstock', '0002_alter_category_company_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
