# Generated by Django 5.0.7 on 2024-08-18 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncstock', '0003_stockadjustment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='product_code',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='totalcurrentinventory',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
