# Generated by Django 6.0.5 on 2026-05-26 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncstock', '0008_alter_inventoryitem_user_alter_stockadjustment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='sku',
        ),
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.category'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.category'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.location'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.category'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncstock.company'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='syncstock.location'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='syncstock.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='syncstock.company'),
        ),
        migrations.DeleteModel(
            name='TotalCurrentInventory',
        ),
    ]
