# Generated by Django 6.0.5 on 2026-05-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncstock', '0009_remove_stockadjustment_product_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='InventoryLoggerItem',
        ),
    ]
